FROM node:14.17.5-alpine

WORKDIR /frontend
COPY ./frontend/package.json /frontend
RUN npm install

# COMPATABILITY ISSUES 
RUN npm uninstall tailwindcss postcss autoprefixer
RUN npm install tailwindcss@npm:@tailwindcss/postcss7-compat @tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9

COPY ./frontend/ /frontend/